services:
  - type: web
    name: order-system-api
    env: dotnet
    plan: free
    region: singapore
    buildCommand: cd database/backend && dotnet publish -c Release -o /app/out
    startCommand: cd database/backend && dotnet OfficeOrderApi.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:5000
      - key: ConnectionStrings__DefaultConnection
        scope: run
        value: Host=db.idyfbtswixhfahddnlkw.supabase.co;Port=5432;Database=postgres;Username=postgres;Password=ReyifmEReyi;SSL Mode=Require;Timeout=15;Command Timeout=15;Max Pool Size=5;Connection Idle Lifetime=5;
      - key: Jwt__Key
        scope: run
        value: YourSuperSecretKeyForJwtTokenGeneration2026!MustBeLongEnough
      - key: Jwt__Issuer
        value: OfficeOrderAPI
      - key: Jwt__Audience
        value: OfficeOrderClient
      - key: Jwt__ExpiryMinutes
        value: 60
